---
name: dartsort
channels:
  - conda-forge
dependencies:
  - python=3.11
  - h5py
  - matplotlib
  - numpy>=1.26
  - pytest
  - scipy>=1.13
  - scikit-learn
  - tqdm
  - pandas
  - linear_operator
  - numba
  - pydantic
  - opt-einsum
